// BBA Course Catalog — 2026-27
// Organized by department and course name

export interface Course {
  id: string;
  name: string;
  department: string;
  canBeCD?: boolean;
}

export const DEPARTMENTS = [
  'English',
  'Social Studies',
  'Mathematics',
  'Science',
  'World Languages',
  'Creative Arts: Media & Performing',
  'Creative Arts: Visual & Design',
  'CS & Engineering',
  'Farm & Food Studies',
  'PE & Wellness',
  'Flexible Pathways',
] as const;

export const COURSES: Course[] = [
  // English
  { id: 'eng1-cp', name: 'CP Humanities 1 (English)', department: 'English' },
  { id: 'eng2-cp', name: 'CP English 2: Literature and Composition', department: 'English' },
  { id: 'eng2-h', name: 'Honors English 2: Literature and Composition', department: 'English' },
  { id: 'eng-outdoor', name: 'CP/Honors Literature, Leadership, and Learning in the Outdoors', department: 'English' },
  { id: 'eng-env-chem', name: 'CP/Honors Environmental Chemistry and Literature', department: 'English' },
  { id: 'eng-cons-bio', name: 'CP/Honors Conservation Biology and Environmental Literacy', department: 'English' },
  { id: 'eng3-cp', name: 'CP English 3: Self, Society, and Identity', department: 'English' },
  { id: 'eng3-h', name: 'Honors English 3: Self, Society, and Identity', department: 'English' },
  { id: 'american-studies-eng', name: 'CP/Honors American Studies (English)', department: 'English' },
  { id: 'ap-lang', name: 'AP English Language and Composition', department: 'English' },
  { id: 'ap-lit', name: 'AP English Literature and Composition', department: 'English' },
  { id: 'creative-writing', name: 'CP Creative Writing', department: 'English' },
  { id: 'eng4-cp', name: 'CP English 4', department: 'English' },
  { id: 'holocaust-eng', name: 'CP Holocaust Studies (English)', department: 'English' },
  { id: 'myth-memoir', name: 'CP Myth and Memoir: Telling Stories', department: 'English' },
  { id: 'neurodiversity-eng', name: 'CP Neurodiversity Studies (English)', department: 'English' },
  { id: 'eld-1', name: 'English Language Arts 1 (ELD)', department: 'English' },
  { id: 'eld-2', name: 'English Language Arts 2 (ELD)', department: 'English' },
  { id: 'eld-3', name: 'English Language Arts 3 (ELD)', department: 'English' },
  { id: 'eld-4', name: 'English Language Arts 4 (ELD)', department: 'English' },
  { id: 'lang-lit', name: 'The Language of Literature', department: 'English' },

  // Social Studies
  { id: 'ss1-cp', name: 'CP Humanities 1 (Social Studies)', department: 'Social Studies' },
  { id: 'ss2-civics', name: 'CP SS 2: Civics, Democracy and Social Change', department: 'Social Studies' },
  { id: 'ss3-world', name: 'CP SS 3: The United States and the World', department: 'Social Studies' },
  { id: 'gov-h', name: 'Honors U.S. Government and Politics', department: 'Social Studies' },
  { id: 'american-studies-ss', name: 'CP/Honors American Studies (Social Studies)', department: 'Social Studies' },
  { id: 'ap-ush', name: 'AP United States History', department: 'Social Studies' },
  { id: 'ancient-world-h', name: 'CP/Honors Ancient World History', department: 'Social Studies' },
  { id: 'climate-change', name: 'CP Climate, Leadership and Change', department: 'Social Studies' },
  { id: 'cons-bio-ss', name: 'CP/Honors Conservation Biology and Environmental Literacy (SS)', department: 'Social Studies' },
  { id: 'contemporary-issues', name: 'CP Contemporary Issues', department: 'Social Studies' },
  { id: 'entrepreneurship', name: 'CP/Honors Entrepreneurship', department: 'Social Studies' },
  { id: 'food-systems-ss', name: 'CP Food Systems (Social Studies)', department: 'Social Studies' },
  { id: 'holocaust-ss', name: 'CP Holocaust Studies (Social Studies)', department: 'Social Studies' },
  { id: 'medieval-history', name: 'CP Medieval History', department: 'Social Studies' },
  { id: 'ap-micro', name: 'AP Microeconomics', department: 'Social Studies' },
  { id: 'military-history', name: 'CP Military History', department: 'Social Studies' },
  { id: 'mun-h', name: 'Honors Model United Nations', department: 'Social Studies' },
  { id: 'psych-cp', name: 'CP Psychology', department: 'Social Studies' },
  { id: 'ap-psych', name: 'AP Psychology', department: 'Social Studies' },
  { id: 'small-biz', name: 'CP Small Business Start-up, Management and Economics', department: 'Social Studies' },

  // Mathematics
  { id: 'math-stem-found', name: 'Foundations of STEM (Math)', department: 'Mathematics' },
  { id: 'alg1-cp', name: 'CP Algebra I', department: 'Mathematics' },
  { id: 'alg1-h', name: 'Honors Algebra 1', department: 'Mathematics' },
  { id: 'geom-conceptual', name: 'Conceptual Geometry', department: 'Mathematics' },
  { id: 'geom-cp', name: 'CP Geometry', department: 'Mathematics' },
  { id: 'geom-h', name: 'Honors Geometry', department: 'Mathematics' },
  { id: 'alg2-cp', name: 'CP Algebra 2', department: 'Mathematics' },
  { id: 'alg2-h', name: 'Honors Algebra 2', department: 'Mathematics' },
  { id: 'precalc-cp', name: 'CP Pre-Calculus', department: 'Mathematics' },
  { id: 'precalc-h', name: 'Honors Pre-Calculus', department: 'Mathematics' },
  { id: 'calc-h', name: 'Honors Calculus', department: 'Mathematics' },
  { id: 'ap-calc-ab', name: 'AP Calculus AB', department: 'Mathematics' },
  { id: 'ap-calc-bc', name: 'AP Calculus BC', department: 'Mathematics' },
  { id: 'data-science', name: 'CP/Honors Data Science', department: 'Mathematics' },
  { id: 'personal-finance', name: 'Personal Finance', department: 'Mathematics' },
  { id: 'stats-cp', name: 'CP/Honors Statistics', department: 'Mathematics' },
  { id: 'ap-stats', name: 'AP Statistics', department: 'Mathematics' },

  // Science
  { id: 'sci-stem-found', name: 'Foundations of STEM (Science)', department: 'Science' },
  { id: 'sci-found', name: 'CP Foundations of Science', department: 'Science' },
  { id: 'phys1-h', name: 'Honors Physics 1', department: 'Science' },
  { id: 'chem-cp', name: 'CP Chemistry', department: 'Science' },
  { id: 'chem-h', name: 'Honors Chemistry', department: 'Science' },
  { id: 'ap-chem', name: 'AP Chemistry', department: 'Science' },
  { id: 'sci-env-chem', name: 'CP/Honors Environmental Chemistry and Literature (Science)', department: 'Science' },
  { id: 'sci-cons-bio', name: 'CP/Honors Conservation Biology and Environmental Literacy (Science)', department: 'Science' },
  { id: 'bio-cp', name: 'CP Biology', department: 'Science' },
  { id: 'bio-h', name: 'Honors Biology', department: 'Science' },
  { id: 'ap-bio', name: 'AP Biology', department: 'Science' },
  { id: 'phys2-ap', name: 'Honors/AP Physics 2', department: 'Science' },
  { id: 'phys-c', name: 'AP Physics C: Mechanics', department: 'Science' },
  { id: 'anat-phys', name: 'CP/Honors Anatomy and Physiology', department: 'Science' },
  { id: 'forensics', name: 'Forensic Science', department: 'Science' },
  { id: 'biotech', name: 'CP/Honors Introduction to Biotechnology', department: 'Science' },
  { id: 'astronomy', name: 'CP/Honors Modern Astronomy: Stars, Galaxies, and the Universe', department: 'Science' },

  // World Languages
  { id: 'fr1', name: 'French 1', department: 'World Languages' },
  { id: 'fr2', name: 'French 2', department: 'World Languages' },
  { id: 'fr3', name: 'French 3', department: 'World Languages' },
  { id: 'fr4h', name: 'Honors French 4/5', department: 'World Languages' },
  { id: 'ap-fr', name: 'AP French', department: 'World Languages' },
  { id: 'de1', name: 'German 1', department: 'World Languages' },
  { id: 'de2', name: 'German 2', department: 'World Languages' },
  { id: 'de3', name: 'German 3', department: 'World Languages' },
  { id: 'de4h', name: 'Honors German 4/5', department: 'World Languages' },
  { id: 'ap-de', name: 'AP German', department: 'World Languages' },
  { id: 'sp1', name: 'Spanish 1', department: 'World Languages' },
  { id: 'sp2', name: 'Spanish 2', department: 'World Languages' },
  { id: 'sp3', name: 'Spanish 3', department: 'World Languages' },
  { id: 'sp4h', name: 'Honors Spanish 4', department: 'World Languages' },
  { id: 'sp5h', name: 'Honors Spanish 5', department: 'World Languages' },
  { id: 'ap-sp', name: 'AP Spanish', department: 'World Languages' },

  // Creative Arts: Media & Performing
  { id: 'dance-found', name: 'Dance: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'dance-studio', name: 'Dance: Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'dance-adv', name: 'Dance: CP Advanced Projects', department: 'Creative Arts: Media & Performing' },
  { id: 'film-cinematography', name: 'Film, Media, and Theater Production: Cinematography', department: 'Creative Arts: Media & Performing' },
  { id: 'film-acting', name: 'Film, Media, and Theater Production: Acting', department: 'Creative Arts: Media & Performing' },
  { id: 'film-directing', name: 'Film, Media, and Theater Production: Directing', department: 'Creative Arts: Media & Performing' },
  { id: 'film-musical', name: 'Film, Media, and Theater Production: Musical Theater', department: 'Creative Arts: Media & Performing' },
  { id: 'film-writing', name: 'Film, Media, and Theater Production: Writing for the Stage and Screen', department: 'Creative Arts: Media & Performing' },
  { id: 'tech-theater', name: 'Technical Theater', department: 'Creative Arts: Media & Performing' },
  { id: 'anim-found', name: 'Digital Animation: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'anim-studio', name: 'Digital Animation: Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'anim-adv', name: 'Digital Animation: CP Advanced Projects', department: 'Creative Arts: Media & Performing' },
  { id: 'photog-found', name: 'Digital Photography: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'photog-studio', name: 'Digital Photography: Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'photog-adv', name: 'Digital Photography: CP Advanced Projects and Portfolio', department: 'Creative Arts: Media & Performing' },
  { id: 'graphic-found', name: 'Digital Graphic Design: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'graphic-studio', name: 'Digital Graphic Design: Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'graphic-adv', name: 'Digital Graphic Design: CP Advanced Projects', department: 'Creative Arts: Media & Performing' },
  { id: 'game-found', name: 'Video Game Design: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'game-studio', name: 'Video Game Design Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'game-adv', name: 'Video Game Design: CP Advanced Projects', department: 'Creative Arts: Media & Performing' },
  { id: 'music-found', name: 'Applied Music: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'music-studio', name: 'Applied Music: Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'music-adv', name: 'Applied Music: CP Advanced Projects', department: 'Creative Arts: Media & Performing' },
  { id: 'music-theory', name: 'CP/Honors Music Theory', department: 'Creative Arts: Media & Performing' },
  { id: 'music-prod-found', name: 'Music Production: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'music-prod-studio', name: 'Music Production: Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'music-prod-adv', name: 'Music Production: CP Advanced Projects', department: 'Creative Arts: Media & Performing' },
  { id: 'vocal-ensemble', name: 'Vocal Music Ensemble', department: 'Creative Arts: Media & Performing' },
  { id: 'vocal-ensemble-adv', name: 'CP Advanced Vocal Music Ensemble', department: 'Creative Arts: Media & Performing' },
  { id: 'inst-ensemble', name: 'Instrumental Music Ensemble', department: 'Creative Arts: Media & Performing' },
  { id: 'inst-ensemble-adv', name: 'CP Advanced Instrumental Music Ensemble', department: 'Creative Arts: Media & Performing' },
  { id: 'music-classic-hist', name: 'CP/Honors Classic Music History', department: 'Creative Arts: Media & Performing' },
  { id: 'music-contemp-hist', name: 'CP/Honors Contemporary Music History', department: 'Creative Arts: Media & Performing' },
  { id: 'music-world', name: 'CP/Honors World Music: A Multicultural Exploration', department: 'Creative Arts: Media & Performing' },
  { id: 'film-scoring-found', name: 'Film Scoring: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'film-scoring-studio', name: 'Film Scoring: Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'film-scoring-adv', name: 'Film Scoring: CP Advanced Projects', department: 'Creative Arts: Media & Performing' },
  { id: 'songwriting-found', name: 'Songwriting: Foundations', department: 'Creative Arts: Media & Performing' },
  { id: 'songwriting-studio', name: 'Songwriting: Studio', department: 'Creative Arts: Media & Performing' },
  { id: 'songwriting-adv', name: 'Songwriting: CP Advanced Projects', department: 'Creative Arts: Media & Performing' },

  // Creative Arts: Visual & Design
  { id: 'art-nature', name: 'Art of Nature', department: 'Creative Arts: Visual & Design' },
  { id: 'ceramics-found', name: 'Ceramics: Foundations', department: 'Creative Arts: Visual & Design' },
  { id: 'ceramics-studio', name: 'Ceramics: Studio', department: 'Creative Arts: Visual & Design' },
  { id: 'ceramics-adv', name: 'Ceramics: CP Advanced Projects', department: 'Creative Arts: Visual & Design' },
  { id: 'design-found', name: 'Design: Foundations', department: 'Creative Arts: Visual & Design' },
  { id: 'design-studio', name: 'Design: Studio', department: 'Creative Arts: Visual & Design' },
  { id: 'design-adv', name: 'Design: CP Advanced Projects', department: 'Creative Arts: Visual & Design' },
  { id: 'visual-art-found', name: 'Visual Art: Foundations in Painting and Drawing', department: 'Creative Arts: Visual & Design' },
  { id: 'visual-art-studio', name: 'Visual Art: Studio Drawing and Painting', department: 'Creative Arts: Visual & Design' },
  { id: 'visual-art-adv', name: 'Visual Art: CP Advanced Projects and Portfolio', department: 'Creative Arts: Visual & Design' },
  { id: 'woodworking-found', name: 'Woodworking: Foundations', department: 'Creative Arts: Visual & Design' },
  { id: 'woodworking-studio', name: 'Woodworking: Studio', department: 'Creative Arts: Visual & Design' },
  { id: 'woodworking-adv', name: 'Woodworking: CP Advanced Projects', department: 'Creative Arts: Visual & Design' },
  { id: 'sculpture-found', name: 'Sculpture: Foundations', department: 'Creative Arts: Visual & Design' },
  { id: 'ap-2d-art', name: 'Independent Study: Honors/AP 2D Art and Design', department: 'Creative Arts: Visual & Design' },
  { id: 'ap-3d-art', name: 'Independent Study: Honors/AP 3D Art and Design', department: 'Creative Arts: Visual & Design' },
  { id: 'jewelry-making', name: 'DE Introduction to Jewelry Making', department: 'Creative Arts: Visual & Design' },

  // CS & Engineering
  { id: 'prog1', name: 'CP Programming 1', department: 'CS & Engineering' },
  { id: 'prog2', name: 'CP Programming 2', department: 'CS & Engineering' },
  { id: 'ap-cs-a', name: 'AP Computer Science A', department: 'CS & Engineering' },
  { id: 'robotics-found', name: 'Robotics: Foundations', department: 'CS & Engineering' },
  { id: 'robotics-adv', name: 'CP/Honors Advanced Robotics and Engineering', department: 'CS & Engineering' },
  { id: 'cad', name: 'CP Engineering Through CAD', department: 'CS & Engineering' },
  { id: 'adv-eng', name: 'CP Advanced Engineering', department: 'CS & Engineering' },
  { id: 'bike-tech', name: 'Project Bike Tech', department: 'CS & Engineering' },

  // Farm & Food Studies
  { id: 'farm-ethnobotany', name: 'CP Ethnobotany: Plants and Humans', department: 'Farm & Food Studies' },
  { id: 'farm-to-plate', name: 'Farm to Plate', department: 'Farm & Food Studies' },
  { id: 'farm-food-systems', name: 'CP Food Systems', department: 'Farm & Food Studies' },
  { id: 'sustainable-ag', name: 'CP Sustainable Agriculture', department: 'Farm & Food Studies' },
  { id: 'farm-internship', name: 'Farm Skills Internship', department: 'Farm & Food Studies' },

  // PE & Wellness
  { id: 'wellness', name: 'Wellness', department: 'PE & Wellness' },
  { id: 'thrive', name: 'CP Thrive: Mind, Body, and Soul', department: 'PE & Wellness' },
  { id: 'group-fitness', name: 'Group Fitness: Cardio, Core, Strength', department: 'PE & Wellness' },
  { id: 'personal-fitness', name: 'Personal Fitness', department: 'PE & Wellness' },
  { id: 'sport-education', name: 'Sport Education', department: 'PE & Wellness' },
  { id: 'sports-medicine', name: 'CP Sports Medicine', department: 'PE & Wellness' },
  { id: 'vermont-place', name: 'Vermont: A Study of Place', department: 'PE & Wellness' },
  { id: 'yoga', name: 'Yoga', department: 'PE & Wellness' },

  // Flexible Pathways
  { id: 'dual-enroll', name: 'Dual Enrollment (General)', department: 'Flexible Pathways' },
  { id: 'college-careers', name: 'Introduction to College and Careers', department: 'Flexible Pathways' },
  { id: 'internship', name: 'Work-Based Learning: Internships', department: 'Flexible Pathways' },
  { id: 'trades', name: 'Tools, Techniques, and the Trades', department: 'Flexible Pathways' },
  { id: 'free', name: 'Free / Study Hall', department: 'Flexible Pathways' },
  { id: 'swtech', name: 'Southwest Tech Program', department: 'Flexible Pathways' },
];

export function getCourseById(id: string): Course | undefined {
  return COURSES.find((c) => c.id === id);
}

export function getCoursesByDepartment(dept: string): Course[] {
  return COURSES.filter((c) => c.department === dept);
}

export interface Teacher {
  name: string;
  email: string;
  role?: string;
  departments: string[];
}

export const TEACHERS: Teacher[] = [
  { name: 'Nicole Abetti', email: 'nabetti@burrburton.org', role: 'English Teacher, International Dorms', departments: ['English'] },
  { name: 'Rebecca Allen', email: 'rlallen@burrburton.org', role: 'Science Teacher', departments: ['Science'] },
  { name: 'Emily Bazan', email: 'ebazan@burrburton.org', role: 'Dance Teacher', departments: ['Creative Arts: Media & Performing'] },
  { name: 'Elpi Blanchard', email: 'eblanchard@burrburton.org', role: 'Science Teacher, Science Dept. Co-Chair', departments: ['Science'] },
  { name: 'Katie Bove', email: 'kbove@burrburton.org', role: 'Spanish Teacher, World Languages Dept. Chair', departments: ['World Languages'] },
  { name: 'Jennifer Bowen', email: 'jbowen@burrburton.org', role: 'World Language and Culture teacher/French', departments: ['World Languages'] },
  { name: 'Hakan Brosnan', email: 'hbrosnan@burrburton.org', role: 'Visual Arts Teacher', departments: ['Creative Arts: Visual & Design'] },
  { name: 'Ollie Brown', email: 'obrown@burrburton.org', role: 'STEM Integrationist', departments: ['CS & Engineering', 'Science', 'Mathematics'] },
  { name: 'Laura Callen', email: 'lcallen@burrburton.org', role: 'Humanities Teacher', departments: ['English', 'Social Studies'] },
  { name: 'Mike Caraco', email: 'mcaraco@burrburton.org', role: 'Dean of Faculty, Math Teacher', departments: ['Mathematics'] },
  { name: 'Isabella Carrabino', email: 'icarrabino@burrburton.org', role: 'Math Teacher', departments: ['Mathematics'] },
  { name: 'Andrew Cassarino', email: 'acassarino@burrburton.org', role: 'Humanities Teacher', departments: ['English', 'Social Studies'] },
  { name: 'Toure Christie', email: 'tchristie@burrburton.org', role: 'Physical Education Teacher', departments: ['PE & Wellness'] },
  { name: 'Scott Clausen', email: 'sclausen@burrburton.org', role: 'English Teacher', departments: ['English'] },
  { name: 'Rabbi Michael Cohen', email: 'mcohen@burrburton.org', role: 'Rabbi', departments: ['Social Studies', 'English'] },
  { name: 'Thom Collins', email: 'tcollins@burrburton.org', role: 'Science Teacher', departments: ['Science'] },
  { name: 'Cheryl Cornwell', email: 'ccornwell@burrburton.org', role: 'English Teacher', departments: ['English'] },
  { name: 'Mrs. Kelly Cray', email: 'kcray@burrburton.org', role: 'Cultural & Language Support Teacher', departments: ['English', 'World Languages'] },
  { name: 'Julie Crosier', email: 'jcrosier@burrburton.org', role: 'Physical Education Teacher, Assistant Athletic Director', departments: ['PE & Wellness'] },
  { name: 'Nick Exler', email: 'nexler@burrburton.org', role: 'Music Teacher', departments: ['Creative Arts: Media & Performing'] },
  { name: 'Julie Freebern', email: 'jfreebern@burrburton.org', role: 'Music Teacher', departments: ['Creative Arts: Media & Performing'] },
  { name: 'Hal Friday', email: 'hfriday@burrburton.org', role: 'Humanities Teacher', departments: ['English', 'Social Studies'] },
  { name: 'Kerri Friday', email: 'kfriday@burrburton.org', role: 'Humanities Teacher', departments: ['English', 'Social Studies'] },
  { name: 'Megan Gault', email: 'mgault@burrburton.org', role: 'Math Teacher, Math Dept. Chair', departments: ['Mathematics'] },
  { name: 'Mr. John Graf III', email: 'jgraf@burrburton.org', role: 'Social Studies Teacher, Social Studies Dept. Chair', departments: ['Social Studies'] },
  { name: 'Garrett Hall', email: 'ghall@burrburton.org', role: 'Science Teacher', departments: ['Science'] },
  { name: 'Jon Hammond', email: 'jhammond@burrburton.org', role: 'Athletic and Mountain Campus Advisor', departments: ['Flexible Pathways'] },
  { name: 'Jessica Handler', email: 'jhandler@burrburton.org', role: 'Math Teacher', departments: ['Mathematics'] },
  { name: 'Erin Harris', email: 'eharris@burrburton.org', role: 'Wellness Teacher', departments: ['PE & Wellness'] },
  { name: 'Dr. Sarah Harris', email: 'sharris@burrburton.org', role: 'Spanish Teacher', departments: ['World Languages'] },
  { name: 'Nora Hefner', email: 'nhefner@burrburton.org', role: 'Science Teacher, Food and Farm Systems Coordinator', departments: ['Science', 'Farm & Food Studies'] },
  { name: 'Cory Herrington', email: 'cherrington@burrburton.org', role: 'Director of Enrollment and Admissions', departments: ['Flexible Pathways'] },
  { name: 'Andrea Hogan', email: 'ahogan@burrburton.org', role: 'School Counselor', departments: ['Flexible Pathways'] },
  { name: 'Jen Hyatt', email: 'jhyatt@burrburton.org', role: 'Academic Dean', departments: ['Flexible Pathways'] },
  { name: 'Karyn Jackson', email: 'kjackson@burrburton.org', role: 'Math Teacher', departments: ['Mathematics'] },
  { name: 'Ms. Jillian Joyce', email: 'jjoyce@burrburton.org', role: 'Social Studies Teacher', departments: ['Social Studies'] },
  { name: 'Kristen Kimball', email: 'kkimball@burrburton.org', role: 'School Counselor, School Counseling Dept. Chair', departments: ['Flexible Pathways'] },
  { name: 'Cori Klein', email: 'cklein@burrburton.org', role: 'Design Space Assistant', departments: ['Creative Arts: Visual & Design', 'CS & Engineering'] },
  { name: 'Tom Klein', email: 'tklein@burrburton.org', role: 'Social Studies Teacher', departments: ['Social Studies'] },
  { name: 'Emily Kohler', email: 'ekohler@burrburton.org', role: 'Program Coordinator for School Counseling and Enrollment', departments: ['Flexible Pathways'] },
  { name: 'Abby Lalor', email: 'alalor@burrburton.org', role: 'Library Assistant', departments: ['Flexible Pathways'] },
  { name: 'Jacque Lewicki', email: 'jlewicki@burrburton.org', role: 'Registrar', departments: ['Flexible Pathways'] },
  { name: 'Kristi Lewicki', email: 'klewicki@burrburton.org', role: 'Multi-Tiered Systems of Support (MTSS) Coordinator', departments: ['Flexible Pathways'] },
  { name: 'Anharad Llewelyn', email: 'allewelyn@burrburton.org', role: 'Visual Arts Teacher', departments: ['Creative Arts: Visual & Design'] },
  { name: 'Ms. Julie McGraw', email: 'jMcGraw@burrburton.org', role: 'Physical Education Teacher, Physical Education Dept. Chair', departments: ['PE & Wellness'] },
  { name: 'Barb Miceli', email: 'bmiceli@burrburton.org', role: 'German Teacher', departments: ['World Languages'] },
  { name: 'Dave Miceli', email: 'dmiceli@burrburton.org', role: 'Athletic Director', departments: ['PE & Wellness'] },
  { name: 'Melissa Michaud', email: 'mmichaud@burrburton.org', role: 'School Counselor', departments: ['Flexible Pathways'] },
  { name: 'Paul Molinelli', email: 'pmolinelli@burrburton.org', role: 'Design, Arts Integration, Design Space Coordinator, Technical Theater', departments: ['Creative Arts: Visual & Design', 'Creative Arts: Media & Performing', 'CS & Engineering'] },
  { name: 'Kevin Morrison', email: 'kmorrison@burrburton.org', role: 'Media Arts Teacher, Media & Performing Arts Dept. Chair', departments: ['Creative Arts: Media & Performing'] },
  { name: 'Jonathan Mowry', email: 'jmowry@burrburton.org', role: 'Woodworking & Design Teacher', departments: ['Creative Arts: Visual & Design'] },
  { name: 'Joe Mundt', email: 'jmundt@burrburton.org', role: 'Math Teacher', departments: ['Mathematics'] },
  { name: 'Ms Amy Newbold', email: 'anewbold@burrburton.org', role: 'Science Teacher', departments: ['Science'] },
  { name: 'Mr. Pete Nicholson', email: 'pnicholson@burrburton.org', role: 'English Teacher', departments: ['English'] },
  { name: 'Jill Perry-Balzano', email: 'jperrybalzano@burrburton.org', role: 'Director of Communications', departments: ['Flexible Pathways'] },
  { name: 'Sean Powers', email: 'spowers@burrburton.org', role: 'Visual Arts Teacher', departments: ['Creative Arts: Visual & Design'] },
  { name: 'Nicole Preiser', email: 'npreiser@burrburton.org', role: 'Science Teacher, Science Dept. Co-Chair', departments: ['Science'] },
  { name: 'Margi Putney', email: 'mputney@burrburton.org', role: 'Media and Library Specialist', departments: ['Flexible Pathways'] },
  { name: 'James Raposa', email: 'jraposa@burrburton.org', role: 'Director of Drama, Dance, and Tech Theater', departments: ['Creative Arts: Media & Performing'] },
  { name: 'John Roche', email: 'jroche@burrburton.org', role: 'Cinematography Teacher', departments: ['Creative Arts: Media & Performing'] },
  { name: 'Ms. Cristin Rose', email: 'crose@burrburton.org', role: 'School Counselor', departments: ['Flexible Pathways'] },
  { name: 'Katy Schonbeck', email: 'kschonbeck@burrburton.org', role: 'Math Teacher', departments: ['Mathematics'] },
  { name: 'Ms. Kim Shaw', email: 'kshaw@burrburton.org', role: 'Spanish Teacher', departments: ['World Languages'] },
  { name: 'Bea Smith', email: 'bsmith@burrburton.org', role: 'Staff', departments: ['Flexible Pathways'] },
  { name: 'Nancy Strain', email: 'nstrain@burrburton.org', role: 'English Teacher, English Dept. Chair', departments: ['English'] },
  { name: 'Eric Strebel', email: 'estrebel@burrburton.org', role: 'Humanities Teacher', departments: ['English', 'Social Studies'] },
  { name: 'Kelsey Towslee', email: 'ktowslee@burrburton.org', role: 'Athletic Trainer', departments: ['PE & Wellness'] },
  { name: 'Kelly Travis', email: 'ktravis@burrburton.org', role: 'Math Teacher', departments: ['Mathematics'] },
  { name: 'Alexander Vincent', email: 'avincent@burrburton.org', role: 'Graphic Design and Photography Teacher', departments: ['Creative Arts: Visual & Design', 'Creative Arts: Media & Performing'] },
  { name: 'Melanie Virgilio', email: 'mvirgilio@burrburton.org', role: 'Visual Arts Teacher', departments: ['Creative Arts: Visual & Design'] },
  { name: 'Thomas von Allmen', email: 'tvonallmen@burrburton.org', role: 'Social Studies Teacher', departments: ['Social Studies'] },
  { name: 'Mr. Jonathan Wilson', email: 'jwilson@burrburton.org', role: 'Social Studies Teacher', departments: ['Social Studies'] },
  { name: 'Madison Wilson', email: 'mwilson@burrburton.org', role: 'Staff', departments: ['Flexible Pathways'] },
  { name: 'Karen Witalec-Krupa', email: 'kwitaleckrupa@burrburton.org', role: 'English Teacher', departments: ['English'] },
  { name: 'Ms. Amy Wright', email: 'awright@burrburton.org', role: 'Director of Technology', departments: ['CS & Engineering', 'Flexible Pathways'] },
  { name: 'Patrick Zilkha', email: 'Pzilkha@burrburton.org', role: 'Math Teacher', departments: ['Mathematics'] },
];

export function getTeachersByDepartment(dept: string): Teacher[] {
  return TEACHERS.filter((t) => t.departments.includes(dept));
}

